# Generated by Django 5.1.1 on 2025-02-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('days', models.PositiveIntegerField()),
                ('travel_group', models.CharField(choices=[('family', 'Family'), ('couple', 'Couple'), ('friends', 'Friends'), ('solo', 'Solo')], max_length=20)),
                ('activities', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
