# Generated by Django 5.1.1 on 2025-02-16 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0002_tripplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TripPlan',
        ),
    ]
