# Generated by Django 5.1.1 on 2025-04-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0004_city_attraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
