# Generated by Django 5.1.1 on 2025-04-06 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0005_booking_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='mobile_no',
        ),
    ]
