# Generated by Django 5.1.1 on 2025-04-12 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0006_remove_booking_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('license_number', models.CharField(max_length=20)),
                ('license_expiry', models.DateField()),
                ('experience_years', models.IntegerField()),
                ('rating', models.IntegerField(default=4)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='trail.bus')),
            ],
        ),
        migrations.CreateModel(
            name='FlightCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('role', models.CharField(max_length=50)),
                ('experience_years', models.IntegerField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='trail.flight')),
            ],
        ),
        migrations.CreateModel(
            name='TrainCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('role', models.CharField(max_length=50)),
                ('experience_years', models.IntegerField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='trail.train')),
            ],
        ),
    ]
